In [40]:
import pandas as pd
import numpy as np
import matplotlib as plt
pd.set_option('display.max_columns', None)

try:
    df = pd.read_csv("heart_attack_dataset (1).csv")
except FileNotFoundError:
    print("File not found")

In [42]:
df.head(10)

,Age,Gender,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,Diet,StressLevel,Ethnicity,Income,EducationLevel,Medication,ChestPainType,ECGResults,MaxHeartRate,ST_Depression,ExerciseInducedAngina,Slope,NumberOfMajorVessels,Thalassemia,PreviousHeartAttack,StrokeHistory,Residence,EmploymentStatus,MaritalStatus,Outcome
0,31,Male,194,162,71,22.9,0,1,0,0,6,0,Unhealthy,1,Hispanic,64510,High School,Yes,Typical,ST-T abnormality,173,0.52,Yes,Downsloping,1,Normal,0,0,Suburban,Retired,Single,No Heart Attack
1,69,Male,208,148,93,33.9,1,1,0,0,1,2,Unhealthy,6,Asian,91773,College,No,Atypical,LV hypertrophy,189,3.79,Yes,Upsloping,2,Normal,0,0,Suburban,Unemployed,Married,No Heart Attack
2,34,Female,132,161,94,34.0,0,0,1,1,1,3,Healthy,3,Black,173550,College,No,Non-anginal,Normal,122,0.17,Yes,Upsloping,0,Normal,1,0,Rural,Retired,Single,Heart Attack
3,53,Male,268,134,91,35.0,0,1,1,0,6,0,Healthy,3,Hispanic,43861,High School,Yes,Atypical,ST-T abnormality,104,0.67,Yes,Flat,0,Reversible defect,1,0,Suburban,Retired,Widowed,No Heart Attack
4,57,Female,203,140,75,30.1,0,1,0,0,4,1,Moderate,1,Hispanic,83404,High School,Yes,Typical,ST-T abnormality,126,5.00,Yes,Flat,0,Fixed defect,1,0,Rural,Retired,Married,Heart Attack
5,41,Male,158,154,72,38.7,0,1,0,1,3,2,Moderate,4,Other,113011,High School,Yes,Non-anginal,LV hypertrophy,155,4.30,No,Downsloping,2,Reversible defect,0,0,Rural,Unemployed,Married,Heart Attack
6,45,Female,237,168,114,21.7,0,0,0,0,0,2,Healthy,5,Hispanic,61069,Postgraduate,Yes,Non-anginal,LV hypertrophy,171,2.48,No,Downsloping,0,Fixed defect,1,1,Rural,Retired,Widowed,No Heart Attack
7,61,Female,218,113,115,23.1,0,1,0,1,4,4,Healthy,5,Asian,74686,College,No,Asymptomatic,ST-T abnormality,101,2.81,Yes,Downsloping,1,Fixed defect,1,0,Suburban,Unemployed,Widowed,No Heart Attack
8,45,Male,216,114,72,24.8,0,1,0,1,2,4,Unhealthy,2,White,148763,Postgraduate,No,Non-anginal,Normal,174,2.23,No,Upsloping,3,Fixed defect,0,1,Urban,Retired,Divorced,Heart Attack
9,30,Male,143,130,91,24.7,1,1,0,0,6,2,Moderate,3,Black,184885,High School,Yes,Asymptomatic,LV hypertrophy,130,3.02,No,Upsloping,0,Normal,0,1,Urban,Unemployed,Married,No Heart Attack

In [12]:
df.shape

(372974, 32)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 372974 entries, 0 to 372973
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Age                    372974 non-null  int64
 1   Gender                 372974 non-null  str
 2   Cholesterol            372974 non-null  int64
 3   BloodPressure          372974 non-null  int64
 4   HeartRate              372974 non-null  int64
 5   BMI                    372974 non-null  float64
 6   Smoker                 372974 non-null  int64
 7   Diabetes               372974 non-null  int64
 8   Hypertension           372974 non-null  int64
 9   FamilyHistory          372974 non-null  int64
 10  PhysicalActivity       372974 non-null  int64
 11  AlcoholConsumption     372974 non-null  int64
 12  Diet                   372974 non-null  str
 13  StressLevel            372974 non-null  int64
 14  Ethnicity              372974 non-null  str
 15  Income                 372974 non-null  int64
 16  EducationLevel         372974 non-null  str
 17  Medication             372974 non-null  str
 18  ChestPainType          372974 non-null  str
 19  ECGResults             372974 non-null  str
 20  MaxHeartRate           372974 non-null  int64
 21  ST_Depression          372974 non-null  float64
 22  ExerciseInducedAngina  372974 non-null  str
 23  Slope                  372974 non-null  str
 24  NumberOfMajorVessels   372974 non-null  int64
 25  Thalassemia            372974 non-null  str
 26  PreviousHeartAttack    372974 non-null  int64
 27  StrokeHistory          372974 non-null  int64
 28  Residence              372974 non-null  str
 29  EmploymentStatus       372974 non-null  str
 30  MaritalStatus          372974 non-null  str
 31  Outcome                372974 non-null  str
dtypes: float64(2), int64(16), str(14)
memory usage: 130.0 MB

In [25]:
df["Gender"].dtype

In [15]:
df.describe()

,Age,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,StressLevel,Income,MaxHeartRate,ST_Depression,NumberOfMajorVessels,PreviousHeartAttack,StrokeHistory
count,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000
mean,56.975151,199.455844,134.508234,89.495043,29.006733,0.499225,0.500987,0.500973,0.499901,3.003475,2.000048,5.001885,110033.409913,149.463896,2.501799,1.498525,0.496938,0.500815
std,15.867016,57.723381,25.984528,17.342658,6.345460,0.500000,0.500000,0.500000,0.500001,2.000114,1.414572,2.582025,51961.721991,28.849990,1.443696,1.118003,0.499991,0.500000
min,30.000000,100.000000,90.000000,60.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,20000.000000,100.000000,0.000000,0.000000,0.000000,0.000000
25%,43.000000,149.000000,112.000000,74.000000,23.500000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.000000,64957.250000,124.000000,1.250000,0.000000,0.000000,0.000000
50%,57.000000,199.000000,134.000000,89.000000,29.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,5.000000,110111.000000,149.000000,2.500000,1.000000,0.000000,1.000000
75%,71.000000,249.000000,157.000000,105.000000,34.500000,1.000000,1.000000,1.000000,1.000000,5.000000,3.000000,7.000000,155012.000000,174.000000,3.750000,2.000000,1.000000,1.000000
max,84.000000,299.000000,179.000000,119.000000,40.000000,1.000000,1.000000,1.000000,1.000000,6.000000,4.000000,9.000000,199999.000000,199.000000,5.000000,3.000000,1.000000,1.000000

In [24]:
cont_col = [col for col in df.columns if df[col].nunique() != 2]
for col in cont_col:
    zero_col = (df[col] == 0).sum()
    pct_zero = (zero_col / len(df)) * 100
    print(f"{col}: {pct_zero}%")

Age: 0.0%
Cholesterol: 0.0%
BloodPressure: 0.0%
HeartRate: 0.0%
BMI: 0.0%
PhysicalActivity: 14.243620198726989%
AlcoholConsumption: 19.981017443575155%
Diet: 0.0%
StressLevel: 0.0%
Ethnicity: 0.0%
Income: 0.0%
EducationLevel: 0.0%
ChestPainType: 0.0%
ECGResults: 0.0%
MaxHeartRate: 0.0%
ST_Depression: 0.10778231190377882%
Slope: 0.0%
NumberOfMajorVessels: 25.027481808383428%
Thalassemia: 0.0%
Residence: 0.0%
EmploymentStatus: 0.0%
MaritalStatus: 0.0%

### Observation 
-No missing values
-few outliers, nothing alarming(most parameters seemed to be within reference range)
-All zero values were checked and rechecked, and all seem valid

In [27]:
#Convert type str to object in cat variables
str_cols = df.select_dtypes(include="string").columns
df[str_cols] = df[str_cols].astype(object)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 372974 entries, 0 to 372973
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Age                    372974 non-null  int64
 1   Gender                 372974 non-null  object
 2   Cholesterol            372974 non-null  int64
 3   BloodPressure          372974 non-null  int64
 4   HeartRate              372974 non-null  int64
 5   BMI                    372974 non-null  float64
 6   Smoker                 372974 non-null  int64
 7   Diabetes               372974 non-null  int64
 8   Hypertension           372974 non-null  int64
 9   FamilyHistory          372974 non-null  int64
 10  PhysicalActivity       372974 non-null  int64
 11  AlcoholConsumption     372974 non-null  int64
 12  Diet                   372974 non-null  object
 13  StressLevel            372974 non-null  int64
 14  Ethnicity              372974 non-null  object
 15  Income                 372974 non-null  int64
 16  EducationLevel         372974 non-null  object
 17  Medication             372974 non-null  object
 18  ChestPainType          372974 non-null  object
 19  ECGResults             372974 non-null  object
 20  MaxHeartRate           372974 non-null  int64
 21  ST_Depression          372974 non-null  float64
 22  ExerciseInducedAngina  372974 non-null  object
 23  Slope                  372974 non-null  object
 24  NumberOfMajorVessels   372974 non-null  int64
 25  Thalassemia            372974 non-null  object
 26  PreviousHeartAttack    372974 non-null  int64
 27  StrokeHistory          372974 non-null  int64
 28  Residence              372974 non-null  object
 29  EmploymentStatus       372974 non-null  object
 30  MaritalStatus          372974 non-null  object
 31  Outcome                372974 non-null  object
dtypes: float64(2), int64(16), object(14)
memory usage: 91.1+ MB

In [62]:
#Data type grouping 
binary_cols = [col for col in df.columns if df[col].nunique() == 2]
cat_cols = [col for col in df.columns if (col not in binary_cols) & (col not in continuous_cols) & (col != "Outcome")]
continuous_cols = [col for col in df.columns if df[col].nunique() > 25]

In [73]:
binary_maps = {
    'Gender': {"Male": 1, "Female": 0},
    'Medication': {"Yes": 1, "No": 0},
    'ExerciseInducedAngina': {"Yes": 1, "No": 0},
    'Outcome': {"No Heart Attack": 0, "Heart Attack": 1}
    
}

In [75]:
#Binary Encoding
for col, mapping in binary_maps.items():
    df[col] = df[col].map(mapping)

,Age,Gender,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,Diet,StressLevel,Ethnicity,Income,EducationLevel,Medication,ChestPainType,ECGResults,MaxHeartRate,ST_Depression,ExerciseInducedAngina,Slope,NumberOfMajorVessels,Thalassemia,PreviousHeartAttack,StrokeHistory,Residence,EmploymentStatus,MaritalStatus,Outcome
0,31,NaN,194,162,71,22.9,0,1,0,0,6,0,Unhealthy,1,Hispanic,64510,High School,NaN,Typical,ST-T abnormality,173,0.52,NaN,Downsloping,1,Normal,0,0,Suburban,Retired,Single,NaN
1,69,NaN,208,148,93,33.9,1,1,0,0,1,2,Unhealthy,6,Asian,91773,College,NaN,Atypical,LV hypertrophy,189,3.79,NaN,Upsloping,2,Normal,0,0,Suburban,Unemployed,Married,NaN
2,34,NaN,132,161,94,34.0,0,0,1,1,1,3,Healthy,3,Black,173550,College,NaN,Non-anginal,Normal,122,0.17,NaN,Upsloping,0,Normal,1,0,Rural,Retired,Single,NaN
3,53,NaN,268,134,91,35.0,0,1,1,0,6,0,Healthy,3,Hispanic,43861,High School,NaN,Atypical,ST-T abnormality,104,0.67,NaN,Flat,0,Reversible defect,1,0,Suburban,Retired,Widowed,NaN
4,57,NaN,203,140,75,30.1,0,1,0,0,4,1,Moderate,1,Hispanic,83404,High School,NaN,Typical,ST-T abnormality,126,5.00,NaN,Flat,0,Fixed defect,1,0,Rural,Retired,Married,NaN

In [ ]:
df[]

In [75]:
#Binary Encoding
for col, mapping in binary_maps.items():
    df[col] = df[col].map(mapping)
df.head()

,Age,Gender,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,Diet,StressLevel,Ethnicity,Income,EducationLevel,Medication,ChestPainType,ECGResults,MaxHeartRate,ST_Depression,ExerciseInducedAngina,Slope,NumberOfMajorVessels,Thalassemia,PreviousHeartAttack,StrokeHistory,Residence,EmploymentStatus,MaritalStatus,Outcome
0,31,NaN,194,162,71,22.9,0,1,0,0,6,0,Unhealthy,1,Hispanic,64510,High School,NaN,Typical,ST-T abnormality,173,0.52,NaN,Downsloping,1,Normal,0,0,Suburban,Retired,Single,NaN
1,69,NaN,208,148,93,33.9,1,1,0,0,1,2,Unhealthy,6,Asian,91773,College,NaN,Atypical,LV hypertrophy,189,3.79,NaN,Upsloping,2,Normal,0,0,Suburban,Unemployed,Married,NaN
2,34,NaN,132,161,94,34.0,0,0,1,1,1,3,Healthy,3,Black,173550,College,NaN,Non-anginal,Normal,122,0.17,NaN,Upsloping,0,Normal,1,0,Rural,Retired,Single,NaN
3,53,NaN,268,134,91,35.0,0,1,1,0,6,0,Healthy,3,Hispanic,43861,High School,NaN,Atypical,ST-T abnormality,104,0.67,NaN,Flat,0,Reversible defect,1,0,Suburban,Retired,Widowed,NaN
4,57,NaN,203,140,75,30.1,0,1,0,0,4,1,Moderate,1,Hispanic,83404,High School,NaN,Typical,ST-T abnormality,126,5.00,NaN,Flat,0,Fixed defect,1,0,Rural,Retired,Married,NaN